var all_diseases = [
    {
        "code": "spontaneous pneumothorax",
        "description": "",
        "display_name": "Spontaneous pneumothorax",
        "keywords": [
            "Pneumothorax",
            "collapsed lung",
            "pneumothorax",
            "pneumothorax (diagnosis)",
            "pneumothorax disorder",
            "pneumothorax nos",
            "pneumothorax, nos",
            "pneumothorax, unspecified",
            "Pneumothorax",
            "collapsed lung",
            "pneumothorax",
            "pneumothorax (diagnosis)",
            "pneumothorax disorder",
            "pneumothorax nos",
            "pneumothorax, nos",
            "pneumothorax, unspecified"
        ]
    },
    {
        "code": "cluster headache",
        "description": "",
        "display_name": "Cluster headache",
        "keywords": [
            "Cluster Headache",
            "cephalalgia, paroxysmal, nocturnal, orbital",
            "cluster headache",
            "cluster headaches",
            "headache histamine",
            "headache vasomotor",
            "headache, cluster",
            "headache;cluster",
            "histamine cephalgia",
            "histamine headache",
            "horton syndrome",
            "horton's neuralgia",
            "horton's syndrome",
            "hortons syndrome",
            "migrainous neuralgia",
            "neuralgia, ciliary",
            "neuralgias, ciliary",
            "syndrome, horton",
            "Cluster Headache",
            "cephalalgia, paroxysmal, nocturnal, orbital",
            "cluster headache",
            "cluster headaches",
            "headache histamine",
            "headache vasomotor",
            "headache, cluster",
            "headache;cluster",
            "histamine cephalgia",
            "histamine headache",
            "horton syndrome",
            "horton's neuralgia",
            "horton's syndrome",
            "hortons syndrome",
            "migrainous neuralgia",
            "neuralgia, ciliary",
            "neuralgias, ciliary",
            "syndrome, horton"
        ]
    },
    {
        "code": "boerhaave",
        "description": "",
        "display_name": "Boerhaave",
        "keywords": []
    },
    {
        "code": "spontaneous rib fracture",
        "description": "",
        "display_name": "Spontaneous rib fracture",
        "keywords": [
            "Rib Fractures",
            "costal fracture",
            "fracture of rib",
            "fracture of rib, nos",
            "fracture rib",
            "fracture, rib",
            "fracture; rib",
            "fracture;rib(s)",
            "fractured rib",
            "fractured rib(s)",
            "fractured ribs",
            "fractures, rib",
            "rib fracture",
            "rib fractures",
            "rib, fracture",
            "Rib Fractures",
            "costal fracture",
            "fracture of rib",
            "fracture of rib, nos",
            "fracture rib",
            "fracture, rib",
            "fracture; rib",
            "fracture;rib(s)",
            "fractured rib",
            "fractured rib(s)",
            "fractured ribs",
            "fractures, rib",
            "rib fracture",
            "rib fractures",
            "rib, fracture"
        ]
    },
    {
        "code": "gerd",
        "description": "",
        "display_name": "GERD",
        "keywords": [
            "Gastroesophageal reflux disease",
            "acid reflux",
            "esophageal reflux",
            "gastroesophageal reflux",
            "gastroesophageal reflux disease",
            "gastrooesophageal reflux",
            "gastrooesophageal reflux disease",
            "ge reflux",
            "gerd - gastro-esophageal reflux disease",
            "gord - gastro-esophageal reflux disease",
            "oesophageal reflux",
            "reflux esophageal",
            "reflux; gastroesophageal",
            "Gastroesophageal reflux disease",
            "acid reflux",
            "esophageal reflux",
            "gastroesophageal reflux",
            "gastroesophageal reflux disease",
            "gastrooesophageal reflux",
            "gastrooesophageal reflux disease",
            "ge reflux",
            "gerd - gastro-esophageal reflux disease",
            "gord - gastro-esophageal reflux disease",
            "oesophageal reflux",
            "reflux esophageal",
            "reflux; gastroesophageal"
        ]
    },
    {
        "code": "hiv (initial infection)",
        "description": "",
        "display_name": "HIV (initial infection)",
        "keywords": [
            "Communicable Diseases",
            "communicable disease",
            "communicable diseases",
            "disease, communicable",
            "disease, infectious",
            "diseases, communicable",
            "infection",
            "infectious disease",
            "infectious diseases",
            "Infection",
            "infection",
            "infection (diagnosis)",
            "infections",
            "HIV Infections",
            "diseases due to immunodeficiency virus",
            "hiv - human immunodeficiency virus infection",
            "hiv disease",
            "hiv infection",
            "hiv infection nos",
            "hiv infections",
            "htlv iii infections",
            "htlv iii lav infections",
            "human immunodeficiency virus [hiv] disease",
            "human immunodeficiency virus disease",
            "human immunodeficiency virus infection (disorder)",
            "infection, htlv-iii",
            "infection; hiv disease as cause",
            "infections, hiv",
            "unspecified human immunodeficiency virus [hiv] disease",
            "HIV Vaccine",
            "hiv",
            "hiv vaccine",
            "hiv vaccine (medication)",
            "hiv vaccines",
            "hiv/aids vaccines",
            "human immunodeficiency virus vaccine",
            "vaccine hiv",
            "vaccine, hiv",
            "vaccines viral hiv",
            "Communicable Diseases",
            "communicable disease",
            "communicable diseases",
            "disease, communicable",
            "disease, infectious",
            "diseases, communicable",
            "infection",
            "infectious disease",
            "infectious diseases",
            "Infection",
            "infection",
            "infection (diagnosis)",
            "infections",
            "HIV Infections",
            "diseases due to immunodeficiency virus",
            "hiv - human immunodeficiency virus infection",
            "hiv disease",
            "hiv infection",
            "hiv infection nos",
            "hiv infections",
            "htlv iii infections",
            "htlv iii lav infections",
            "human immunodeficiency virus [hiv] disease",
            "human immunodeficiency virus disease",
            "human immunodeficiency virus infection (disorder)",
            "infection, htlv-iii",
            "infection; hiv disease as cause",
            "infections, hiv",
            "unspecified human immunodeficiency virus [hiv] disease",
            "HIV Vaccine",
            "hiv",
            "hiv vaccine",
            "hiv vaccine (medication)",
            "hiv vaccines",
            "hiv/aids vaccines",
            "human immunodeficiency virus vaccine",
            "vaccine hiv",
            "vaccine, hiv",
            "vaccines viral hiv"
        ]
    },
    {
        "code": "anemia",
        "description": "",
        "display_name": "Anemia",
        "keywords": [
            "Anemia",
            "anaemia",
            "anaemia, nos",
            "anaemia, unspecified",
            "anemia",
            "anemia (diagnosis)",
            "anemia, nos",
            "anemias",
            "unspecified anaemia",
            "Anemia",
            "anaemia",
            "anaemia, nos",
            "anaemia, unspecified",
            "anemia",
            "anemia (diagnosis)",
            "anemia, nos",
            "anemias",
            "unspecified anaemia"
        ]
    },
    {
        "code": "viral pharyngitis",
        "description": "",
        "display_name": "Viral pharyngitis",
        "keywords": [
            "Viral pharyngitis",
            "pharyngitis viral",
            "pharyngitis viral nos",
            "pharyngitis; viral",
            "sore throat; viral",
            "sore throats viral",
            "viral pharyngitis",
            "viral pharyngitis (diagnosis)",
            "viral pharyngitis (disorder)",
            "viral pharyngitis, nos",
            "viral sore throat",
            "viral sore throat nos",
            "virus; pharyngitis",
            "virus; sore throat",
            "Viral pharyngitis",
            "pharyngitis viral",
            "pharyngitis viral nos",
            "pharyngitis; viral",
            "sore throat; viral",
            "sore throats viral",
            "viral pharyngitis",
            "viral pharyngitis (diagnosis)",
            "viral pharyngitis (disorder)",
            "viral pharyngitis, nos",
            "viral sore throat",
            "viral sore throat nos",
            "virus; pharyngitis",
            "virus; sore throat"
        ]
    },
    {
        "code": "inguinal hernia",
        "description": "",
        "display_name": "Inguinal hernia",
        "keywords": [
            "Inguinal region",
            "groin",
            "groins",
            "inguinal",
            "inguinal region",
            "inguinal region structure (body structure)",
            "inguinal region, nos",
            "inguinal regions",
            "Inguinal region",
            "groin",
            "groins",
            "inguinal",
            "inguinal region",
            "inguinal region structure (body structure)",
            "inguinal region, nos",
            "inguinal regions"
        ]
    },
    {
        "code": "myasthenia gravis",
        "description": "",
        "display_name": "Myasthenia gravis",
        "keywords": [
            "Myasthenias",
            "fatigable weakness",
            "fatigable weakness of limb muscles",
            "generalised muscle weakness due to defect at the neuromuscular junction",
            "generalized muscle weakness (due to defect at the neuromuscular junction)",
            "generalized muscle weakness due to defect at the neuromuscular junction",
            "myasthenia",
            "myasthenias",
            "myasthenic weakness",
            "proximal muscle weakness due to defect at the neuromuscular junction",
            "Myasthenias",
            "fatigable weakness",
            "fatigable weakness of limb muscles",
            "generalised muscle weakness due to defect at the neuromuscular junction",
            "generalized muscle weakness (due to defect at the neuromuscular junction)",
            "generalized muscle weakness due to defect at the neuromuscular junction",
            "myasthenia",
            "myasthenias",
            "myasthenic weakness",
            "proximal muscle weakness due to defect at the neuromuscular junction"
        ]
    },
    {
        "code": "whooping cough",
        "description": "",
        "display_name": "Whooping cough",
        "keywords": [
            "Whooping respiration",
            "whoop",
            "whooping",
            "whooping respiration",
            "whooping respiration (finding)",
            "whoops",
            "Coughing",
            "cough",
            "cough, nos",
            "coughing",
            "coughing - function",
            "coughs",
            "observation of cough",
            "Whooping respiration",
            "whoop",
            "whooping",
            "whooping respiration",
            "whooping respiration (finding)",
            "whoops",
            "Coughing",
            "cough",
            "cough, nos",
            "coughing",
            "coughing - function",
            "coughs",
            "observation of cough"
        ]
    },
    {
        "code": "anaphylaxis",
        "description": "",
        "display_name": "Anaphylaxis",
        "keywords": [
            "allergic shock",
            "anaphylactic reaction",
            "anaphylactic shock",
            "anaphylactic syndrome",
            "anaphylaxis",
            "anaphylaxis (diagnosis)",
            "anaphylaxis (disorder)",
            "reaction, anaphylactic",
            "systemic anaphylaxis",
            "Anaphylactic shock",
            "anaphylactic reaction",
            "anaphylactic reactions",
            "anaphylactic shock",
            "anaphylactic shock, unspecified",
            "anaphylaxis",
            "reaction, anaphylactoid",
            "shock due to anaphylaxis",
            "shock, anaphylactic",
            "shock, anaphylactoid",
            "shock; allergy",
            "shock; anaphylactic",
            "systemic anaphylaxis",
            "allergic shock",
            "anaphylactic reaction",
            "anaphylactic shock",
            "anaphylactic syndrome",
            "anaphylaxis",
            "anaphylaxis (diagnosis)",
            "anaphylaxis (disorder)",
            "reaction, anaphylactic",
            "systemic anaphylaxis",
            "Anaphylactic shock",
            "anaphylactic reaction",
            "anaphylactic reactions",
            "anaphylactic shock",
            "anaphylactic shock, unspecified",
            "anaphylaxis",
            "reaction, anaphylactoid",
            "shock due to anaphylaxis",
            "shock, anaphylactic",
            "shock, anaphylactoid",
            "shock; allergy",
            "shock; anaphylactic",
            "systemic anaphylaxis"
        ]
    },
    {
        "code": "epiglottitis",
        "description": "",
        "display_name": "Epiglottitis",
        "keywords": [
            "Epiglottitis",
            "epiglottitides",
            "epiglottitis",
            "epiglottitis (diagnosis)",
            "epiglottitis (disorder)",
            "epiglottitis nos",
            "epiglottitis, nos",
            "Epiglottitis",
            "epiglottitides",
            "epiglottitis",
            "epiglottitis (diagnosis)",
            "epiglottitis (disorder)",
            "epiglottitis nos",
            "epiglottitis, nos"
        ]
    },
    {
        "code": "guillain-barr\u00e9 syndrome",
        "description": "",
        "display_name": "Guillain-Barr\u00e9 syndrome",
        "keywords": [
            "Guillain-Barre Syndrome",
            "barr\u00e9-guillain",
            "guillain barre disease",
            "guillain barre syndrome",
            "guillain-barre syndrome",
            "guillain-barre syndrome (gbs)",
            "guillain-barr\u00e9 syndrome (disorder)",
            "guillain-barr\u00e9 syndromes",
            "guillaine-barre syndrome",
            "landry-guillain-barre syndrome",
            "landry; paralysis",
            "syndrome, guillain-barre",
            "syndrome, guillain-barr\u00e9",
            "syndrome, guillaine-barre",
            "syndrome, landry-guillain-barre",
            "Guillain-Barre Syndrome",
            "barr\u00e9-guillain",
            "guillain barre disease",
            "guillain barre syndrome",
            "guillain-barre syndrome",
            "guillain-barre syndrome (gbs)",
            "guillain-barr\u00e9 syndrome (disorder)",
            "guillain-barr\u00e9 syndromes",
            "guillaine-barre syndrome",
            "landry-guillain-barre syndrome",
            "landry; paralysis",
            "syndrome, guillain-barre",
            "syndrome, guillain-barr\u00e9",
            "syndrome, guillaine-barre",
            "syndrome, landry-guillain-barre"
        ]
    },
    {
        "code": "acute laryngitis",
        "description": "",
        "display_name": "Acute laryngitis",
        "keywords": [
            "Acute laryngitis",
            "acute laryngitis",
            "acute laryngitis (diagnosis)",
            "acute laryngitis (disorder)",
            "acute laryngitis nos",
            "laryngitis (acute)",
            "laryngitis (acute) nos",
            "laryngitis acute",
            "laryngitis acute nos",
            "laryngitis, acute",
            "laryngitis;acute",
            "Acute laryngitis",
            "acute laryngitis",
            "acute laryngitis (diagnosis)",
            "acute laryngitis (disorder)",
            "acute laryngitis nos",
            "laryngitis (acute)",
            "laryngitis (acute) nos",
            "laryngitis acute",
            "laryngitis acute nos",
            "laryngitis, acute",
            "laryngitis;acute"
        ]
    },
    {
        "code": "croup",
        "description": "",
        "display_name": "Croup",
        "keywords": [
            "Subglottic laryngitis",
            "croup",
            "laryngitis",
            "pseudocroup",
            "spasmodic croup",
            "subglottic laryngitis",
            "viral croup",
            "Croup",
            "acute laryngotracheobronchitis",
            "acute obstructive laryngitis",
            "acute obstructive laryngitis [croup]",
            "croup",
            "croup (diagnosis)",
            "croup syndrome",
            "laryngotracheobronchitis, acute",
            "laryngotracheobronchitis; acute",
            "Subglottic laryngitis",
            "croup",
            "laryngitis",
            "pseudocroup",
            "spasmodic croup",
            "subglottic laryngitis",
            "viral croup",
            "Croup",
            "acute laryngotracheobronchitis",
            "acute obstructive laryngitis",
            "acute obstructive laryngitis [croup]",
            "croup",
            "croup (diagnosis)",
            "croup syndrome",
            "laryngotracheobronchitis, acute",
            "laryngotracheobronchitis; acute"
        ]
    },
    {
        "code": "psvt",
        "description": "",
        "display_name": "PSVT",
        "keywords": [
            "Paroxysmal supraventricular tachycardia",
            "episodic supraventricular tachycardia",
            "paroxysmal supraventricular tachycardia",
            "paroxysmal supraventricular tachycardia (disorder)",
            "paroxysmal supraventricular tachycardia (psvt)",
            "paroxysmal supraventricular tachycardias",
            "paroxysmal tachycardia (supraventricular)",
            "paroxysmal; tachycardia, supraventricular",
            "psvt",
            "supraventricular tachycardia paroxysmal",
            "supraventricular tachycardia, paroxysmal",
            "tachycardia, paroxysmal supraventricular",
            "tachycardia;supraventr;paroxys",
            "Paroxysmal supraventricular tachycardia",
            "episodic supraventricular tachycardia",
            "paroxysmal supraventricular tachycardia",
            "paroxysmal supraventricular tachycardia (disorder)",
            "paroxysmal supraventricular tachycardia (psvt)",
            "paroxysmal supraventricular tachycardias",
            "paroxysmal tachycardia (supraventricular)",
            "paroxysmal; tachycardia, supraventricular",
            "psvt",
            "supraventricular tachycardia paroxysmal",
            "supraventricular tachycardia, paroxysmal",
            "tachycardia, paroxysmal supraventricular",
            "tachycardia;supraventr;paroxys"
        ]
    },
    {
        "code": "atrial fibrillation",
        "description": "",
        "display_name": "Atrial fibrillation",
        "keywords": [
            "Atrial Fibrillation",
            "atrial fibrillation",
            "atrial fibrillations",
            "fibrillation atrial",
            "fibrillations, atrial",
            "Atrial Fibrillation",
            "atrial fibrillation",
            "atrial fibrillations",
            "fibrillation atrial",
            "fibrillations, atrial"
        ]
    },
    {
        "code": "bronchiectasis",
        "description": "",
        "display_name": "Bronchiectasis",
        "keywords": [
            "Bronchiectasis",
            "bronchi dilated",
            "bronchiectases",
            "bronchiectasis",
            "bronchiectasis (disorder)",
            "bronchiectasis nos",
            "bronchiectasis, nos",
            "chronic dilatation of bronchus and bronchiole",
            "permanent enlargement of the airways of the lungs",
            "Bronchiectasis",
            "bronchi dilated",
            "bronchiectases",
            "bronchiectasis",
            "bronchiectasis (disorder)",
            "bronchiectasis nos",
            "bronchiectasis, nos",
            "chronic dilatation of bronchus and bronchiole",
            "permanent enlargement of the airways of the lungs"
        ]
    },
    {
        "code": "allergic sinusitis",
        "description": "",
        "display_name": "Allergic sinusitis",
        "keywords": [
            "Sinusitis",
            "infection, sinus",
            "infections, sinus",
            "sinus infection",
            "sinus infections",
            "sinus; infection",
            "sinusitides",
            "sinusitis",
            "sinusitis (diagnosis)",
            "sinusitis nos",
            "sinusitis, nos",
            "Sinusitis",
            "infection, sinus",
            "infections, sinus",
            "sinus infection",
            "sinus infections",
            "sinus; infection",
            "sinusitides",
            "sinusitis",
            "sinusitis (diagnosis)",
            "sinusitis nos",
            "sinusitis, nos"
        ]
    },
    {
        "code": "chagas",
        "description": "",
        "display_name": "Chagas",
        "keywords": []
    },
    {
        "code": "scombroid food poisoning",
        "description": "",
        "display_name": "Scombroid food poisoning",
        "keywords": [
            "Food allergenic extracts",
            "food",
            "food allergenic extracts",
            "Poisoning",
            "poisoning",
            "poisoning (disorder)",
            "poisoning by",
            "poisoning nos",
            "poisoning, nos",
            "poisonings",
            "Food allergenic extracts",
            "food",
            "food allergenic extracts",
            "Poisoning",
            "poisoning",
            "poisoning (disorder)",
            "poisoning by",
            "poisoning nos",
            "poisoning, nos",
            "poisonings"
        ]
    },
    {
        "code": "myocarditis",
        "description": "",
        "display_name": "Myocarditis",
        "keywords": [
            "Myocarditis",
            "myocarditides",
            "myocarditis",
            "myocarditis (diagnosis)",
            "myocarditis (disorder)",
            "myocarditis nos",
            "myocarditis, nos",
            "myocarditis, unspecified",
            "Myocarditis",
            "myocarditides",
            "myocarditis",
            "myocarditis (diagnosis)",
            "myocarditis (disorder)",
            "myocarditis nos",
            "myocarditis, nos",
            "myocarditis, unspecified"
        ]
    },
    {
        "code": "larygospasm",
        "description": "",
        "display_name": "Larygospasm",
        "keywords": []
    },
    {
        "code": "acute dystonic reactions",
        "description": "",
        "display_name": "Acute dystonic reactions",
        "keywords": []
    },
    {
        "code": "localized edema",
        "description": "",
        "display_name": "Localized edema",
        "keywords": [
            "Localized Edema",
            "edema; localized",
            "local edema",
            "local oedema",
            "localised oedema",
            "localized edema",
            "localized edema (finding)",
            "localized edema (morphologic abnormality)",
            "localized edema nos",
            "localized oedema",
            "localized; edema",
            "oedema;localised",
            "Localized Edema",
            "edema; localized",
            "local edema",
            "local oedema",
            "localised oedema",
            "localized edema",
            "localized edema (finding)",
            "localized edema (morphologic abnormality)",
            "localized edema nos",
            "localized oedema",
            "localized; edema",
            "oedema;localised"
        ]
    },
    {
        "code": "sle",
        "description": "",
        "display_name": "SLE",
        "keywords": [
            "Lupus Erythematosus, Systemic",
            "lupus erythematosus systemic",
            "lupus erythematosus, systemic",
            "lupus, erythematosus, systemic",
            "sle",
            "systemic lupus erythematosis",
            "systemic lupus erythematosus",
            "Lupus Erythematosus, Systemic",
            "lupus erythematosus systemic",
            "lupus erythematosus, systemic",
            "lupus, erythematosus, systemic",
            "sle",
            "systemic lupus erythematosis",
            "systemic lupus erythematosus"
        ]
    },
    {
        "code": "tuberculosis",
        "description": "",
        "display_name": "Tuberculosis",
        "keywords": [
            "Tuberculosis",
            "infection due to mycobacterium tuberculosis",
            "infection tuberculosis",
            "infection; tuberculous",
            "mtb - mycobacterium tuberculosis infection",
            "mycobacterium tuberculosis infections",
            "tb",
            "tb - tuberculosis",
            "tuberculoses",
            "tuberculosis",
            "tuberculosis (tb)",
            "tuberculosis nos",
            "tuberculous",
            "Tuberculosis",
            "infection due to mycobacterium tuberculosis",
            "infection tuberculosis",
            "infection; tuberculous",
            "mtb - mycobacterium tuberculosis infection",
            "mycobacterium tuberculosis infections",
            "tb",
            "tb - tuberculosis",
            "tuberculoses",
            "tuberculosis",
            "tuberculosis (tb)",
            "tuberculosis nos",
            "tuberculous"
        ]
    },
    {
        "code": "unstable angina",
        "description": "",
        "display_name": "Unstable angina",
        "keywords": [
            "Angina, Unstable",
            "angina at rest",
            "angina pectoris; at rest",
            "angina unstable",
            "crescendo angina",
            "crescendo; angina",
            "impending infarction",
            "intermediate coronary syndrome",
            "preinfarctional; angina",
            "rest angina",
            "rest; angina",
            "unstable angina",
            "unstable angina pectoris",
            "unstable angina pectoris (diagnosis)",
            "unstable anginas",
            "worsening angina",
            "Angina, Unstable",
            "angina at rest",
            "angina pectoris; at rest",
            "angina unstable",
            "crescendo angina",
            "crescendo; angina",
            "impending infarction",
            "intermediate coronary syndrome",
            "preinfarctional; angina",
            "rest angina",
            "rest; angina",
            "unstable angina",
            "unstable angina pectoris",
            "unstable angina pectoris (diagnosis)",
            "unstable anginas",
            "worsening angina"
        ]
    },
    {
        "code": "stable angina",
        "description": "",
        "display_name": "Stable angina",
        "keywords": [
            "Stable angina",
            "angina pectori, stable",
            "angina pectoris, stable",
            "angina stable",
            "angina, chronic stable",
            "angina, stable",
            "anginas, chronic stable",
            "chronic stable angina",
            "pectori, stable angina",
            "pectoris, stable angina",
            "stable angina",
            "stable angina (diagnosis)",
            "stable angina pectori",
            "stable angina pectoris",
            "stable angina, chronic",
            "stable anginas",
            "stable anginas, chronic",
            "stable chronic angina",
            "Stable angina",
            "angina pectori, stable",
            "angina pectoris, stable",
            "angina stable",
            "angina, chronic stable",
            "angina, stable",
            "anginas, chronic stable",
            "chronic stable angina",
            "pectori, stable angina",
            "pectoris, stable angina",
            "stable angina",
            "stable angina (diagnosis)",
            "stable angina pectori",
            "stable angina pectoris",
            "stable angina, chronic",
            "stable anginas",
            "stable anginas, chronic",
            "stable chronic angina"
        ]
    },
    {
        "code": "ebola",
        "description": "",
        "display_name": "Ebola",
        "keywords": [
            "Hemorrhagic Fever, Ebola",
            "ebola",
            "ebola fever hemorrhagic",
            "ebola haemorrhagic fever",
            "ebola hemorrhagic fever",
            "ebola virus disease",
            "ebola virus infection",
            "ebolavirus infection",
            "infection, ebola",
            "infection, ebolavirus",
            "viral haemorrhagic fever, ebola",
            "viral hemorrhagic fever, ebola",
            "virus infection, ebola",
            "Hemorrhagic Fever, Ebola",
            "ebola",
            "ebola fever hemorrhagic",
            "ebola haemorrhagic fever",
            "ebola hemorrhagic fever",
            "ebola virus disease",
            "ebola virus infection",
            "ebolavirus infection",
            "infection, ebola",
            "infection, ebolavirus",
            "viral haemorrhagic fever, ebola",
            "viral hemorrhagic fever, ebola",
            "virus infection, ebola"
        ]
    },
    {
        "code": "acute otitis media",
        "description": "",
        "display_name": "Acute otitis media",
        "keywords": [
            "Acute otitis media",
            "acute media otitis",
            "acute middle ear infection",
            "acute otitis media",
            "acute otitis media (diagnosis)",
            "acute otitis media (disorder)",
            "acute otitis media nos",
            "acute otitis media, nos",
            "aom - acute otitis media",
            "otitis media acute",
            "otitis media acute nos",
            "otitis media;acute",
            "otitis; media, acute",
            "Acute otitis media",
            "acute media otitis",
            "acute middle ear infection",
            "acute otitis media",
            "acute otitis media (diagnosis)",
            "acute otitis media (disorder)",
            "acute otitis media nos",
            "acute otitis media, nos",
            "aom - acute otitis media",
            "otitis media acute",
            "otitis media acute nos",
            "otitis media;acute",
            "otitis; media, acute"
        ]
    },
    {
        "code": "panic attack",
        "description": "",
        "display_name": "Panic attack",
        "keywords": []
    },
    {
        "code": "bronchospasm / acute asthma exacerbation",
        "description": "",
        "display_name": "Bronchospasm / acute asthma exacerbation",
        "keywords": [
            "Bronchospasm",
            "bronchial spasm",
            "bronchospasm",
            "bronchospasm nos",
            "bronchospasms",
            "bronchus; constriction",
            "constriction; bronchus",
            "spasm bronchial",
            "spasms, bronchial",
            "Bronchospasm",
            "bronchial spasm",
            "bronchospasm",
            "bronchospasm nos",
            "bronchospasms",
            "bronchus; constriction",
            "constriction; bronchus",
            "spasm bronchial",
            "spasms, bronchial"
        ]
    },
    {
        "code": "bronchitis",
        "description": "",
        "display_name": "Bronchitis",
        "keywords": [
            "Bronchitis",
            "bronchitides",
            "bronchitis",
            "bronchitis nos",
            "bronchitis, nos",
            "Bronchitis",
            "bronchitides",
            "bronchitis",
            "bronchitis nos",
            "bronchitis, nos"
        ]
    },
    {
        "code": "acute copd exacerbation / infection",
        "description": "",
        "display_name": "Acute COPD exacerbation / infection",
        "keywords": [
            "Acute exacerbation of chronic obstructive airways disease",
            "acute copd exacerbation",
            "acute copd exacerbations",
            "acute exacerbation copd",
            "acute exacerbation of chronic obstructive airways disease",
            "acute exacerbation of chronic obstructive airways disease (disorder)",
            "acute exacerbation of chronic obstructive pulmonary disease",
            "acute exacerbation of copd",
            "chronic obstructive pulmonary disease with (acute) exacerbation",
            "copd exacerbation acute",
            "Communicable Diseases",
            "communicable disease",
            "communicable diseases",
            "disease, communicable",
            "disease, infectious",
            "diseases, communicable",
            "infection",
            "infectious disease",
            "infectious diseases",
            "Infection",
            "infection",
            "infection (diagnosis)",
            "infections",
            "Acute exacerbation of chronic obstructive airways disease",
            "acute copd exacerbation",
            "acute copd exacerbations",
            "acute exacerbation copd",
            "acute exacerbation of chronic obstructive airways disease",
            "acute exacerbation of chronic obstructive airways disease (disorder)",
            "acute exacerbation of chronic obstructive pulmonary disease",
            "acute exacerbation of copd",
            "chronic obstructive pulmonary disease with (acute) exacerbation",
            "copd exacerbation acute",
            "Communicable Diseases",
            "communicable disease",
            "communicable diseases",
            "disease, communicable",
            "disease, infectious",
            "diseases, communicable",
            "infection",
            "infectious disease",
            "infectious diseases",
            "Infection",
            "infection",
            "infection (diagnosis)",
            "infections"
        ]
    },
    {
        "code": "pulmonary embolism",
        "description": "",
        "display_name": "Pulmonary embolism",
        "keywords": [
            "Lung",
            "lung",
            "lung structure",
            "lung structure (body structure)",
            "lung, nos",
            "lungs",
            "pulmo",
            "pulmonary",
            "pulmones",
            "respiratory system, lung",
            "set of lungs",
            "structure of lungs, unspecified",
            "Embolism",
            "embolic",
            "embolism",
            "embolism (diagnosis)",
            "embolism (disorder)",
            "embolism nos",
            "embolism, nos",
            "embolisms",
            "Lung",
            "lung",
            "lung structure",
            "lung structure (body structure)",
            "lung, nos",
            "lungs",
            "pulmo",
            "pulmonary",
            "pulmones",
            "respiratory system, lung",
            "set of lungs",
            "structure of lungs, unspecified",
            "Embolism",
            "embolic",
            "embolism",
            "embolism (diagnosis)",
            "embolism (disorder)",
            "embolism nos",
            "embolism, nos",
            "embolisms"
        ]
    },
    {
        "code": "urti",
        "description": "",
        "display_name": "URTI",
        "keywords": []
    },
    {
        "code": "influenza",
        "description": "",
        "display_name": "Influenza",
        "keywords": [
            "Influenza virus vaccine",
            "flu vaccine",
            "flu vaccines",
            "influenza",
            "influenza vaccine",
            "influenza vaccines",
            "influenza virus vaccine",
            "influenza virus vaccine (medication)",
            "influenza, nos",
            "influenza, unspecified formulation",
            "influenzavirus vaccine",
            "influenzavirus vaccines",
            "vaccine, influenza",
            "Influenza",
            "flu",
            "flu syndrome",
            "grippe",
            "human influenza",
            "influenza",
            "influenza nos",
            "influenza, nos",
            "influenzas",
            "syndrome flu",
            "Influenza virus vaccine",
            "flu vaccine",
            "flu vaccines",
            "influenza",
            "influenza vaccine",
            "influenza vaccines",
            "influenza virus vaccine",
            "influenza virus vaccine (medication)",
            "influenza, nos",
            "influenza, unspecified formulation",
            "influenzavirus vaccine",
            "influenzavirus vaccines",
            "vaccine, influenza",
            "Influenza",
            "flu",
            "flu syndrome",
            "grippe",
            "human influenza",
            "influenza",
            "influenza nos",
            "influenza, nos",
            "influenzas",
            "syndrome flu"
        ]
    },
    {
        "code": "pneumonia",
        "description": "",
        "display_name": "Pneumonia",
        "keywords": [
            "Pneumonia",
            "inflammation lungs",
            "lung inflamed",
            "lung inflammation",
            "pneumonia",
            "pneumonia (disorder)",
            "pneumonia, nos",
            "pneumonitis, nos",
            "pulmonary inflammation",
            "Pneumonia",
            "inflammation lungs",
            "lung inflamed",
            "lung inflammation",
            "pneumonia",
            "pneumonia (disorder)",
            "pneumonia, nos",
            "pneumonitis, nos",
            "pulmonary inflammation"
        ]
    },
    {
        "code": "acute rhinosinusitis",
        "description": "",
        "display_name": "Acute rhinosinusitis",
        "keywords": [
            "Rhinosinusitis",
            "rhinosinusitis",
            "rhinosinusitis (diagnosis)",
            "rhinosinusitis (disorder)",
            "Rhinosinusitis",
            "rhinosinusitis",
            "rhinosinusitis (diagnosis)",
            "rhinosinusitis (disorder)"
        ]
    },
    {
        "code": "chronic rhinosinusitis",
        "description": "",
        "display_name": "Chronic rhinosinusitis",
        "keywords": [
            "Chronic sinusitis",
            "chronic infection of sinus",
            "chronic infection of sinus, nos",
            "chronic infection sinus",
            "chronic rhinosinusitis",
            "chronic rhinosinusitis (diagnosis)",
            "chronic sinus infection",
            "chronic sinusitis",
            "chronic sinusitis (disorder)",
            "chronic sinusitis nos",
            "chronic sinusitis, unspecified",
            "chronic unspecified sinusitis",
            "rhinosinusitis chronic",
            "sinusitis, chronic",
            "sinusitis;chronic",
            "unspecified sinusitis (chronic)",
            "Chronic sinusitis",
            "chronic infection of sinus",
            "chronic infection of sinus, nos",
            "chronic infection sinus",
            "chronic rhinosinusitis",
            "chronic rhinosinusitis (diagnosis)",
            "chronic sinus infection",
            "chronic sinusitis",
            "chronic sinusitis (disorder)",
            "chronic sinusitis nos",
            "chronic sinusitis, unspecified",
            "chronic unspecified sinusitis",
            "rhinosinusitis chronic",
            "sinusitis, chronic",
            "sinusitis;chronic",
            "unspecified sinusitis (chronic)"
        ]
    },
    {
        "code": "bronchiolitis",
        "description": "",
        "display_name": "Bronchiolitis",
        "keywords": [
            "Bronchiolitis",
            "bronchiolitides",
            "bronchiolitis",
            "bronchiolitis (diagnosis)",
            "bronchiolitis, nos",
            "inflammation of the bronchioles",
            "respiratory bronchiolitis",
            "Bronchiolitis",
            "bronchiolitides",
            "bronchiolitis",
            "bronchiolitis (diagnosis)",
            "bronchiolitis, nos",
            "inflammation of the bronchioles",
            "respiratory bronchiolitis"
        ]
    },
    {
        "code": "pulmonary neoplasm",
        "description": "",
        "display_name": "Pulmonary neoplasm",
        "keywords": [
            "Lung Neoplasms",
            "lung neoplasm",
            "lung neoplasm nos",
            "lung neoplasms",
            "lung tumor",
            "lung tumors",
            "lung tumour",
            "lungs--tumors",
            "neoplasm of lung",
            "neoplasm of lung (disorder)",
            "neoplasm of the lung",
            "neoplasm, pulmonary",
            "neoplasms, pulmonary",
            "pulmonary neoplasia",
            "pulmonary neoplasm",
            "pulmonary neoplasms (diagnosis)",
            "tumor of lung",
            "tumour of lung",
            "Lung Neoplasms",
            "lung neoplasm",
            "lung neoplasm nos",
            "lung neoplasms",
            "lung tumor",
            "lung tumors",
            "lung tumour",
            "lungs--tumors",
            "neoplasm of lung",
            "neoplasm of lung (disorder)",
            "neoplasm of the lung",
            "neoplasm, pulmonary",
            "neoplasms, pulmonary",
            "pulmonary neoplasia",
            "pulmonary neoplasm",
            "pulmonary neoplasms (diagnosis)",
            "tumor of lung",
            "tumour of lung"
        ]
    },
    {
        "code": "possible nstemi / stemi",
        "description": "",
        "display_name": "Possible NSTEMI / STEMI",
        "keywords": [
            "Non-ST Elevated Myocardial Infarction",
            "infarction, non-st-elevation myocardial",
            "infarctions, non-st-elevation myocardial",
            "myocardial infarction, non-st-elevation",
            "myocardial infarctions, non-st-elevation",
            "non st elevated myocardial infarction",
            "non st elevation myocardial infarction",
            "non-st elevated myocardial infarction",
            "non-st-elevation myocardial infarction",
            "non-st-elevation myocardial infarctions",
            "nstemi",
            "ST segment elevation myocardial infarction",
            "st elevated myocardial infarction",
            "st elevation myocardial infarction",
            "st segment elevation myocardial infarction",
            "stemi",
            "Non-ST Elevated Myocardial Infarction",
            "infarction, non-st-elevation myocardial",
            "infarctions, non-st-elevation myocardial",
            "myocardial infarction, non-st-elevation",
            "myocardial infarctions, non-st-elevation",
            "non st elevated myocardial infarction",
            "non st elevation myocardial infarction",
            "non-st elevated myocardial infarction",
            "non-st-elevation myocardial infarction",
            "non-st-elevation myocardial infarctions",
            "nstemi",
            "ST segment elevation myocardial infarction",
            "st elevated myocardial infarction",
            "st elevation myocardial infarction",
            "st segment elevation myocardial infarction",
            "stemi"
        ]
    },
    {
        "code": "sarcoidosis",
        "description": "",
        "display_name": "Sarcoidosis",
        "keywords": [
            "Sarcoidosis",
            "benign lymphogranulomatosis of schaumann",
            "benign lymphogranulomatosis, schaumann's",
            "besnier boeck schaumann syndrome",
            "besnier-boeck-schaumann syndrome",
            "boeck's disease",
            "boecks sarcoid",
            "disease, schaumann",
            "sarcoid",
            "sarcoid; darier-roussy",
            "sarcoidosis",
            "sarcoidosis (disorder)",
            "schaumann's syndrome",
            "Sarcoidosis",
            "benign lymphogranulomatosis of schaumann",
            "benign lymphogranulomatosis, schaumann's",
            "besnier boeck schaumann syndrome",
            "besnier-boeck-schaumann syndrome",
            "boeck's disease",
            "boecks sarcoid",
            "disease, schaumann",
            "sarcoid",
            "sarcoid; darier-roussy",
            "sarcoidosis",
            "sarcoidosis (disorder)",
            "schaumann's syndrome"
        ]
    },
    {
        "code": "pancreatic neoplasm",
        "description": "",
        "display_name": "Pancreatic neoplasm",
        "keywords": [
            "Pancreas",
            "exocrine and endocrine pancreas, nos",
            "gastrointestinal tract, pancreas",
            "pancreas",
            "pancreatic",
            "pancreatic structure",
            "structure of pancreas",
            "Pancreatic Hormones",
            "hormones pancreas",
            "hormones, pancreatic",
            "pancreas hormone",
            "pancreatic",
            "pancreatic hormone",
            "pancreatic hormone (substance)",
            "pancreatic hormone preparation",
            "pancreatic hormone preparation, nos",
            "pancreatic hormone, nos",
            "pancreatic hormone-containing product",
            "pancreatic hormones",
            "product containing pancreatic hormone (product)",
            "Neoplasms",
            "malignant, benign, and unspecified neoplasms, cysts, polyps (diagnosis)",
            "neoplasia",
            "neoplasm",
            "neoplasm - benign, malignant, unspecified (including cysts, polyps)",
            "neoplasm nos",
            "neoplasms",
            "new growth",
            "ng - new growth",
            "tumor",
            "tumor nos",
            "tumor, nos",
            "tumors",
            "tumour",
            "Pancreas",
            "exocrine and endocrine pancreas, nos",
            "gastrointestinal tract, pancreas",
            "pancreas",
            "pancreatic",
            "pancreatic structure",
            "structure of pancreas",
            "Pancreatic Hormones",
            "hormones pancreas",
            "hormones, pancreatic",
            "pancreas hormone",
            "pancreatic",
            "pancreatic hormone",
            "pancreatic hormone (substance)",
            "pancreatic hormone preparation",
            "pancreatic hormone preparation, nos",
            "pancreatic hormone, nos",
            "pancreatic hormone-containing product",
            "pancreatic hormones",
            "product containing pancreatic hormone (product)",
            "Neoplasms",
            "malignant, benign, and unspecified neoplasms, cysts, polyps (diagnosis)",
            "neoplasia",
            "neoplasm",
            "neoplasm - benign, malignant, unspecified (including cysts, polyps)",
            "neoplasm nos",
            "neoplasms",
            "new growth",
            "ng - new growth",
            "tumor",
            "tumor nos",
            "tumor, nos",
            "tumors",
            "tumour"
        ]
    },
    {
        "code": "acute pulmonary edema",
        "description": "",
        "display_name": "Acute pulmonary edema",
        "keywords": [
            "Acute pulmonary edema",
            "acute edema of lung",
            "acute edema of lung, nos",
            "acute edema of lung, unspecified",
            "acute edema pulmonary",
            "acute oedema of lung",
            "acute oedema of lung, nos",
            "acute oedema of lung, unspecified",
            "acute pulmonary edema",
            "acute pulmonary edema (diagnosis)",
            "acute pulmonary edema (disorder)",
            "acute pulmonary edema, nos",
            "acute pulmonary oedema",
            "acute pulmonary oedema, nos",
            "oedema;pulmonary;acute",
            "pulmonary acute edema",
            "pulmonary edema acute",
            "pulmonary oedema - acute",
            "Acute pulmonary edema",
            "acute edema of lung",
            "acute edema of lung, nos",
            "acute edema of lung, unspecified",
            "acute edema pulmonary",
            "acute oedema of lung",
            "acute oedema of lung, nos",
            "acute oedema of lung, unspecified",
            "acute pulmonary edema",
            "acute pulmonary edema (diagnosis)",
            "acute pulmonary edema (disorder)",
            "acute pulmonary edema, nos",
            "acute pulmonary oedema",
            "acute pulmonary oedema, nos",
            "oedema;pulmonary;acute",
            "pulmonary acute edema",
            "pulmonary edema acute",
            "pulmonary oedema - acute"
        ]
    },
    {
        "code": "pericarditis",
        "description": "",
        "display_name": "Pericarditis",
        "keywords": [
            "Pericarditis",
            "pericarditis",
            "pericarditis (diagnosis)",
            "pericarditis nos",
            "pericarditis, nos",
            "pericardium; inflammation",
            "swelling or irritation of membrane around heart",
            "Pericarditis",
            "pericarditis",
            "pericarditis (diagnosis)",
            "pericarditis nos",
            "pericarditis, nos",
            "pericardium; inflammation",
            "swelling or irritation of membrane around heart"
        ]
    },
    {
        "code": "abdomen",
        "description": "",
        "display_name": "abdomen",
        "keywords": [
            "Abdominal Cavity",
            "abdomen",
            "abdominal cavities",
            "abdominal cavity",
            "abdominal cavity structure",
            "abdominal cavity, nos",
            "cavitas abdominalis",
            "cavitas abdominis",
            "cavities, abdominal",
            "cavity of abdominal compartment",
            "cavity of compartment of abdomen",
            "cavity, abdominal",
            "intraabdominal",
            "space of abdominal compartment",
            "Abdomen",
            "abdomen",
            "abdomen (volume)",
            "abdomen and",
            "abdomen+",
            "abdomen, nos",
            "abdomens",
            "abdominal",
            "abdominopelvic region",
            "abdominopelvic regions",
            "structure of abdominopelvic cavity and/or content of abdominopelvic cavity and/or anterior abdominal wall (body structure)",
            "Abdominal Cavity",
            "abdomen",
            "abdominal cavities",
            "abdominal cavity",
            "abdominal cavity structure",
            "abdominal cavity, nos",
            "cavitas abdominalis",
            "cavitas abdominis",
            "cavities, abdominal",
            "cavity of abdominal compartment",
            "cavity of compartment of abdomen",
            "cavity, abdominal",
            "intraabdominal",
            "space of abdominal compartment",
            "Abdomen",
            "abdomen",
            "abdomen (volume)",
            "abdomen and",
            "abdomen+",
            "abdomen, nos",
            "abdomens",
            "abdominal",
            "abdominopelvic region",
            "abdominopelvic regions",
            "structure of abdominopelvic cavity and/or content of abdominopelvic cavity and/or anterior abdominal wall (body structure)"
        ]
    },
    {
        "code": "lung disease",
        "description": "",
        "display_name": "Lung disease",
        "keywords": [
            "Lung diseases",
            "disease of lung, nos",
            "diseases of the lung",
            "diseases pulmonary",
            "diseases, pulmonary",
            "disorder lung",
            "lung disease",
            "lung disease nos",
            "lung diseases",
            "lung disorder",
            "lung disorders",
            "lungs--diseases",
            "pneumopathy",
            "pulmonary disease",
            "pulmonary disorder",
            "pulmonary disorders",
            "Chest>Lung",
            "chest>lung",
            "lung",
            "Lung",
            "lung",
            "lung structure",
            "lung structure (body structure)",
            "lung, nos",
            "lungs",
            "pulmo",
            "pulmonary",
            "pulmones",
            "respiratory system, lung",
            "set of lungs",
            "structure of lungs, unspecified",
            "Disease",
            "clinical disease and/or syndrome",
            "clinical disease or syndrome present",
            "clinical disease or syndrome, nos",
            "diagnoses, syndromes, and conditions (diagnosis)",
            "disease",
            "disease (disorder)",
            "disease (or disorder)",
            "disease or disorder",
            "disease or syndrome present",
            "disease or syndrome present, nos",
            "disease, nos",
            "disease/disorder",
            "diseases",
            "disorder",
            "disorders",
            "Lung diseases",
            "disease of lung, nos",
            "diseases of the lung",
            "diseases pulmonary",
            "diseases, pulmonary",
            "disorder lung",
            "lung disease",
            "lung disease nos",
            "lung diseases",
            "lung disorder",
            "lung disorders",
            "lungs--diseases",
            "pneumopathy",
            "pulmonary disease",
            "pulmonary disorder",
            "pulmonary disorders",
            "Chest>Lung",
            "chest>lung",
            "lung",
            "Lung",
            "lung",
            "lung structure",
            "lung structure (body structure)",
            "lung, nos",
            "lungs",
            "pulmo",
            "pulmonary",
            "pulmones",
            "respiratory system, lung",
            "set of lungs",
            "structure of lungs, unspecified",
            "Disease",
            "clinical disease and/or syndrome",
            "clinical disease or syndrome present",
            "clinical disease or syndrome, nos",
            "diagnoses, syndromes, and conditions (diagnosis)",
            "disease",
            "disease (disorder)",
            "disease (or disorder)",
            "disease or disorder",
            "disease or syndrome present",
            "disease or syndrome present, nos",
            "disease, nos",
            "disease/disorder",
            "diseases",
            "disorder",
            "disorders"
        ]
    },
    {
        "code": "heart disease",
        "description": "",
        "display_name": "Heart disease",
        "keywords": [
            "Heart Diseases",
            "cardiac disease",
            "cardiac diseases",
            "cardiac disorder",
            "cardiac disorders",
            "cardiopathy",
            "disease disorders heart",
            "disease hearts",
            "disorder cardiac (nos)",
            "heart disease",
            "heart disease (diagnosis)",
            "heart disease nos",
            "heart disease, unspecified",
            "heart diseases",
            "heart diseases: general terms",
            "heart disorders",
            "heart--diseases",
            "morbus; cordis",
            "rndx cardiac",
            "Heart Diseases",
            "cardiac disease",
            "cardiac diseases",
            "cardiac disorder",
            "cardiac disorders",
            "cardiopathy",
            "disease disorders heart",
            "disease hearts",
            "disorder cardiac (nos)",
            "heart disease",
            "heart disease (diagnosis)",
            "heart disease nos",
            "heart disease, unspecified",
            "heart diseases",
            "heart diseases: general terms",
            "heart disorders",
            "heart--diseases",
            "morbus; cordis",
            "rndx cardiac"
        ]
    }
];

var all_antecendent_values = [
    {
        "code": "anxiety",
        "display_name": "Anxiety",
        "question": "Do you feel anxious?",
        "description": "patient feels anxious",
        "keywords": []
    },
    {
        "code": "high bp",
        "display_name": "High Bp",
        "question": "Are you consulting because you have high blood pressure?",
        "description": "patient has high BP (high blood pressure)",
        "keywords": [
            "Hypertensive disease",
            "blood pressure high",
            "blood pressure; high",
            "blood pressures, high",
            "elevated blood pressure",
            "high blood pressure",
            "high blood pressures",
            "hypertension",
            "hypertensive disease",
            "hypertensive disease, nos",
            "hypertensive diseases",
            "Hypertensive disease",
            "blood pressure high",
            "blood pressure; high",
            "blood pressures, high",
            "elevated blood pressure",
            "high blood pressure",
            "high blood pressures",
            "hypertension",
            "hypertensive disease",
            "hypertensive disease, nos",
            "hypertensive diseases"
        ]
    },
    {
        "code": "surgery",
        "display_name": "Surgery",
        "question": "Have you had surgery within the last month?",
        "description": "patient had a surgery withing the last month",
        "keywords": []
    },
    {
        "code": "pregnancy",
        "display_name": "Pregnancy",
        "question": "Do you think you are pregnant or are you currently pregnant?",
        "description": "patient is pregnant or thinks she is pregnant",
        "keywords": []
    },
    {
        "code": "unprotected sex",
        "display_name": "Unprotected Sex",
        "question": "Have you had unprotected sex with more than one partner in the last 6 months?",
        "description": "patient had unprotected sex with more than one partner in the last six months",
        "keywords": []
    },
    {
        "code": "overweight",
        "display_name": "Overweight",
        "question": "Are you significantly overweight compared to people of the same height as you?",
        "description": "patient is significantly overweight compared to people of the same height.",
        "keywords": []
    },
    {
        "code": "sensitive to allergies",
        "display_name": "Sensitive To Allergies",
        "question": "Are you more likely to develop common allergies than the general population?",
        "description": "patient is suseptible (likely to develop) to common allergies than the general population",
        "keywords": [
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)"
        ]
    },
    {
        "code": "cold",
        "display_name": "Cold",
        "question": "Have you had a cold in the last 2 weeks?",
        "description": "patient had a cold in the last two week",
        "keywords": [
            "Common Cold",
            "acute coryza",
            "acute infective rhinitis",
            "acute nasopharyngitis",
            "acute nasopharyngitis [common cold]",
            "acute rhinitis",
            "acute rhinitis (diagnosis)",
            "cold",
            "common cold",
            "common colds",
            "coryza",
            "coryza, acute",
            "infective nasopharyngitis nos",
            "infective rhinitis",
            "nasal catarrh, acute",
            "rhinitis acute",
            "rhinitis infectious",
            "upper respiratory infection viral",
            "Chronic Obstructive Airway Disease",
            "chronic airflow limitation",
            "chronic airway disease",
            "chronic obstructive airway disease",
            "chronic obstructive airway disease nos",
            "chronic obstructive lung disease",
            "chronic obstructive pulmonary disease",
            "chronic obstructive pulmonary diseases",
            "cold",
            "copd",
            "hyperactive airway disease",
            "lung; disease, obstructive (chronic)",
            "obstruction; airway, chronic",
            "obstructive airways disease (chronic)",
            "pulmonary disease, chronic obstructive",
            "Common Cold",
            "acute coryza",
            "acute infective rhinitis",
            "acute nasopharyngitis",
            "acute nasopharyngitis [common cold]",
            "acute rhinitis",
            "acute rhinitis (diagnosis)",
            "cold",
            "common cold",
            "common colds",
            "coryza",
            "coryza, acute",
            "infective nasopharyngitis nos",
            "infective rhinitis",
            "nasal catarrh, acute",
            "rhinitis acute",
            "rhinitis infectious",
            "upper respiratory infection viral",
            "Chronic Obstructive Airway Disease",
            "chronic airflow limitation",
            "chronic airway disease",
            "chronic obstructive airway disease",
            "chronic obstructive airway disease nos",
            "chronic obstructive lung disease",
            "chronic obstructive pulmonary disease",
            "chronic obstructive pulmonary diseases",
            "cold",
            "copd",
            "hyperactive airway disease",
            "lung; disease, obstructive (chronic)",
            "obstruction; airway, chronic",
            "obstructive airways disease (chronic)",
            "pulmonary disease, chronic obstructive",
            "Common Cold",
            "acute coryza",
            "acute infective rhinitis",
            "acute nasopharyngitis",
            "acute nasopharyngitis [common cold]",
            "acute rhinitis",
            "acute rhinitis (diagnosis)",
            "cold",
            "common cold",
            "common colds",
            "coryza",
            "coryza, acute",
            "infective nasopharyngitis nos",
            "infective rhinitis",
            "nasal catarrh, acute",
            "rhinitis acute",
            "rhinitis infectious",
            "upper respiratory infection viral",
            "Chronic Obstructive Airway Disease",
            "chronic airflow limitation",
            "chronic airway disease",
            "chronic obstructive airway disease",
            "chronic obstructive airway disease nos",
            "chronic obstructive lung disease",
            "chronic obstructive pulmonary disease",
            "chronic obstructive pulmonary diseases",
            "cold",
            "copd",
            "hyperactive airway disease",
            "lung; disease, obstructive (chronic)",
            "obstruction; airway, chronic",
            "obstructive airways disease (chronic)",
            "pulmonary disease, chronic obstructive"
        ]
    },
    {
        "code": "crowd",
        "display_name": "Crowd",
        "question": "Do you live with 4 or more people?",
        "description": "patient lives with four or more people",
        "keywords": []
    },
    {
        "code": "underweight",
        "display_name": "Underweight",
        "question": "Is your BMI less than 18.5, or are you underweight?",
        "description": "patient has low BMI (less than 18.5) or is underweight",
        "keywords": []
    },
    {
        "code": "hiv sex",
        "display_name": "Hiv Sex",
        "question": "Have you had sexual intercourse with an HIV-positive partner in the past 12 months?",
        "description": "patient had sexual intercourse with an HIV-positive partner in the past 12 months",
        "keywords": [
            "HIV Infections",
            "diseases due to immunodeficiency virus",
            "hiv - human immunodeficiency virus infection",
            "hiv disease",
            "hiv infection",
            "hiv infection nos",
            "hiv infections",
            "htlv iii infections",
            "htlv iii lav infections",
            "human immunodeficiency virus [hiv] disease",
            "human immunodeficiency virus disease",
            "human immunodeficiency virus infection (disorder)",
            "infection, htlv-iii",
            "infection; hiv disease as cause",
            "infections, hiv",
            "unspecified human immunodeficiency virus [hiv] disease",
            "HIV Vaccine",
            "hiv",
            "hiv vaccine",
            "hiv vaccine (medication)",
            "hiv vaccines",
            "hiv/aids vaccines",
            "human immunodeficiency virus vaccine",
            "vaccine hiv",
            "vaccine, hiv",
            "vaccines viral hiv",
            "HIV Infections",
            "diseases due to immunodeficiency virus",
            "hiv - human immunodeficiency virus infection",
            "hiv disease",
            "hiv infection",
            "hiv infection nos",
            "hiv infections",
            "htlv iii infections",
            "htlv iii lav infections",
            "human immunodeficiency virus [hiv] disease",
            "human immunodeficiency virus disease",
            "human immunodeficiency virus infection (disorder)",
            "infection, htlv-iii",
            "infection; hiv disease as cause",
            "infections, hiv",
            "unspecified human immunodeficiency virus [hiv] disease",
            "HIV Vaccine",
            "hiv",
            "hiv vaccine",
            "hiv vaccine (medication)",
            "hiv vaccines",
            "hiv/aids vaccines",
            "human immunodeficiency virus vaccine",
            "vaccine hiv",
            "vaccine, hiv",
            "vaccines viral hiv",
            "HIV Infections",
            "diseases due to immunodeficiency virus",
            "hiv - human immunodeficiency virus infection",
            "hiv disease",
            "hiv infection",
            "hiv infection nos",
            "hiv infections",
            "htlv iii infections",
            "htlv iii lav infections",
            "human immunodeficiency virus [hiv] disease",
            "human immunodeficiency virus disease",
            "human immunodeficiency virus infection (disorder)",
            "infection, htlv-iii",
            "infection; hiv disease as cause",
            "infections, hiv",
            "unspecified human immunodeficiency virus [hiv] disease",
            "HIV Vaccine",
            "hiv",
            "hiv vaccine",
            "hiv vaccine (medication)",
            "hiv vaccines",
            "hiv/aids vaccines",
            "human immunodeficiency virus vaccine",
            "vaccine hiv",
            "vaccine, hiv",
            "vaccines viral hiv"
        ]
    },
    {
        "code": "poor diet",
        "display_name": "Poor Diet",
        "question": "Do you have a poor diet?",
        "description": "patient has a poor diet",
        "keywords": []
    },
    {
        "code": "premature birth",
        "display_name": "Premature Birth",
        "question": "Were you born prematurely or did you suffer any complication at birth?",
        "description": "patient was born prematurely or suffered some complications at birth",
        "keywords": [
            "Premature Birth",
            "birth premature",
            "birth, preterm",
            "births preterm",
            "births, preterm",
            "delivery preterm",
            "delivery; early onset",
            "early onset of delivery (diagnosis)",
            "early onset; delivery",
            "immature; birth",
            "premature",
            "premature birth",
            "premature childbirth",
            "premature delivery",
            "premature; delivery",
            "prematurity",
            "preterm delivery",
            "Complication",
            "complication",
            "complication, nos",
            "complications",
            "complications medical",
            "medical complication",
            "other complication",
            "Premature Birth",
            "birth premature",
            "birth, preterm",
            "births preterm",
            "births, preterm",
            "delivery preterm",
            "delivery; early onset",
            "early onset of delivery (diagnosis)",
            "early onset; delivery",
            "immature; birth",
            "premature",
            "premature birth",
            "premature childbirth",
            "premature delivery",
            "premature; delivery",
            "prematurity",
            "preterm delivery"
        ]
    },
    {
        "code": "viral infection",
        "display_name": "Viral Infection",
        "question": "Have you recently had a viral infection?",
        "description": "patient had a viral infection recently",
        "keywords": [
            "Communicable Diseases",
            "communicable disease",
            "communicable diseases",
            "disease, communicable",
            "disease, infectious",
            "diseases, communicable",
            "infection",
            "infectious disease",
            "infectious diseases",
            "Infection",
            "infection",
            "infection (diagnosis)",
            "infections",
            "Communicable Diseases",
            "communicable disease",
            "communicable diseases",
            "disease, communicable",
            "disease, infectious",
            "diseases, communicable",
            "infection",
            "infectious disease",
            "infectious diseases",
            "Infection",
            "infection",
            "infection (diagnosis)",
            "infections",
            "Communicable Diseases",
            "communicable disease",
            "communicable diseases",
            "disease, communicable",
            "disease, infectious",
            "diseases, communicable",
            "infection",
            "infectious disease",
            "infectious diseases",
            "Infection",
            "infection",
            "infection (diagnosis)",
            "infections"
        ]
    },
    {
        "code": "ear infection treatment",
        "display_name": "Ear Infection Treatment",
        "question": "Are you currently being treated or have you recently been treated with an oral antibiotic for an ear infection?",
        "description": "patient is currently being treated with oral antibiotic for an ear infection",
        "keywords": [
            "Infection of ear",
            "ear infection",
            "ear infection nos",
            "ear infections",
            "ear--infections",
            "infection of ear",
            "infection, ear",
            "infection; ear",
            "infection;ear",
            "Infection of ear",
            "ear infection",
            "ear infection nos",
            "ear infections",
            "ear--infections",
            "infection of ear",
            "infection, ear",
            "infection; ear",
            "infection;ear",
            "Infection of ear",
            "ear infection",
            "ear infection nos",
            "ear infections",
            "ear--infections",
            "infection of ear",
            "infection, ear",
            "infection; ear",
            "infection;ear"
        ]
    },
    {
        "code": "vaccinations",
        "display_name": "Vaccinations",
        "question": "Are your vaccinations / immunization up to date?",
        "description": "patient has up to date vaccinations / immunization",
        "keywords": [
            "date",
            "date allergenic extract"
        ]
    },
    {
        "code": "decongestants",
        "display_name": "Decongestants",
        "question": "Have you recently taken decongestants or other substances that may have stimulant effects?",
        "description": "patient has recently taken decongestants (medicine for nasal congestion) or other substances that may have stimulant effects",
        "keywords": [
            "Nasal congestion (finding)",
            "blocked nose",
            "congested nose",
            "congestion nasal",
            "congestion of nose",
            "congestion;nasal",
            "nasal congestion",
            "nasal congestion (finding)",
            "nasal passage blockage",
            "nasal passage blockage (stuffiness) (symptom)",
            "nasal stuffiness",
            "stuffed-up nose",
            "stuffy nose"
        ]
    },
    {
        "code": "food allergy",
        "display_name": "Food Allergy",
        "question": "Do you have a known severe food allergy?",
        "description": "patient has a known severe food allergy",
        "keywords": [
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Allergic Reaction",
            "allergic reaction",
            "allergic reaction (diagnosis)",
            "allergic reaction (disorder)",
            "allergic reaction nos",
            "allergic reactions",
            "allergy",
            "allergy.",
            "reaction allergic (nos)",
            "reaction, allergic",
            "reactions, allergic",
            "Food allergenic extracts",
            "food",
            "food allergenic extracts",
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Allergic Reaction",
            "allergic reaction",
            "allergic reaction (diagnosis)",
            "allergic reaction (disorder)",
            "allergic reaction nos",
            "allergic reactions",
            "allergy",
            "allergy.",
            "reaction allergic (nos)",
            "reaction, allergic",
            "reactions, allergic",
            "Food allergenic extracts",
            "food",
            "food allergenic extracts",
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Allergic Reaction",
            "allergic reaction",
            "allergic reaction (diagnosis)",
            "allergic reaction (disorder)",
            "allergic reaction nos",
            "allergic reactions",
            "allergy",
            "allergy.",
            "reaction allergic (nos)",
            "reaction, allergic",
            "reactions, allergic",
            "Food allergenic extracts",
            "food",
            "food allergenic extracts"
        ]
    },
    {
        "code": "server immobility",
        "display_name": "Server Immobility",
        "question": "Have you been unable to move or get up for more than 3 consecutive days within the last 4 weeks?",
        "description": "patient has been unable to move or get up for more than 3 consecutive days within the last 4 weeks",
        "keywords": []
    },
    {
        "code": "asian",
        "display_name": "Asian",
        "question": "Are you of Asian descent?",
        "description": "patient is of Asian descent",
        "keywords": []
    },
    {
        "code": "mentruation 12",
        "display_name": "Mentruation 12",
        "question": "Did you have your first menstrual period before the age of 12?",
        "description": "patient had first menstrual period before the age of 12",
        "keywords": []
    },
    {
        "code": "breastfeed 9",
        "display_name": "Breastfeed 9",
        "question": "Have you breastfed one of your children for more than 9 months?",
        "description": "patient has breastfed a child for more than nine months",
        "keywords": []
    },
    {
        "code": "food tuna cheese",
        "display_name": "Food Tuna Cheese",
        "question": "Did you eat dark-fleshed fish (such as tuna) or Swiss cheese before the reaction occurred?",
        "description": "patient ate dark-fleshed fish (such as tuna) or Swiss cheese before the reaction occurred",
        "keywords": [
            "Food allergenic extracts",
            "food",
            "food allergenic extracts",
            "ae-tuna",
            "tuna",
            "tuna allergenic extract",
            "tuna, unspecified",
            "ae-tuna",
            "tuna",
            "tuna allergenic extract",
            "tuna, unspecified",
            "Ataxia Telangiectasia",
            "at",
            "at1",
            "ata",
            "ataxia telangiectasia",
            "ataxia telangiectasia (louis-bar disease)",
            "ataxia telangiectasia syndrome",
            "ataxia, telangiectasia",
            "ataxia-telangiectasia",
            "ataxia-telangiectasia syndrome",
            "ataxia; telangiectasia",
            "atc",
            "louis-bar syndrome",
            "telangiectasia, cerebello-oculocutaneous",
            "Food allergenic extracts",
            "food",
            "food allergenic extracts",
            "ae-tuna",
            "tuna",
            "tuna allergenic extract",
            "tuna, unspecified"
        ]
    },
    {
        "code": "recent hospitalizaiton",
        "display_name": "Recent Hospitalizaiton",
        "question": "Have you been treated in hospital recently for nausea, agitation, intoxication or aggressive behavior and received medication via an intravenous or intramuscular route?",
        "description": "patient was treated in hospital recently for nausea, agitation, intoxication or aggressive behavior and received medication via an intravenous or intramuscular route",
        "keywords": [
            "Agitation",
            "abnormal excitement",
            "agitated",
            "agitated behavior",
            "agitation",
            "excitement abnormal",
            "feeling agitated",
            "feeling agitated (finding)",
            "restlessness",
            "restlessness marked",
            "Nausea",
            "nausea",
            "nausea (finding)",
            "nausea (symptom)",
            "nausea symptom",
            "nausea symptoms",
            "nauseated",
            "nauseating",
            "nauseous"
        ]
    },
    {
        "code": "asthma",
        "display_name": "Asthma",
        "question": "Do you have asthma or have you ever had to use a bronchodilator in the past?",
        "description": "patient has asthma or have used a bronchodilator in the past",
        "keywords": [
            "Asthma",
            "airway hyperreactivity",
            "asthma",
            "asthma (disorder)",
            "asthma disorders",
            "asthma, bronchial",
            "asthma, unspecified",
            "asthmas",
            "bronchial asthma",
            "Asthma",
            "airway hyperreactivity",
            "asthma",
            "asthma (disorder)",
            "asthma disorders",
            "asthma, bronchial",
            "asthma, unspecified",
            "asthmas",
            "bronchial asthma",
            "Asthma",
            "airway hyperreactivity",
            "asthma",
            "asthma (disorder)",
            "asthma disorders",
            "asthma, bronchial",
            "asthma, unspecified",
            "asthmas",
            "bronchial asthma"
        ]
    },
    {
        "code": "ashtma attack hospital",
        "display_name": "Asthma Attack Hospital",
        "question": "Have you been hospitalized for an asthma attack in the past year?",
        "description": "patient was hospitalized for an asthma attack in the past year",
        "keywords": [
            "Asthma attack",
            "asthma attack",
            "asthma attack (diagnosis)",
            "asthma attacks",
            "asthmatic attack",
            "Asthma attack",
            "asthma attack",
            "asthma attack (diagnosis)",
            "asthma attacks",
            "asthmatic attack"
        ]
    },
    {
        "code": "ashtma attack frequency",
        "display_name": "Asthma Attack Frequency",
        "question": "Have you had 2 or more asthma attacks in the past year?",
        "description": "patient had two or more asthma attacks in the past year",
        "keywords": [
            "Asthma attack",
            "asthma attack",
            "asthma attack (diagnosis)",
            "asthma attacks",
            "asthmatic attack",
            "Asthma attack",
            "asthma attack",
            "asthma attack (diagnosis)",
            "asthma attacks",
            "asthmatic attack"
        ]
    },
    {
        "code": "allergy",
        "display_name": "Allergy",
        "question": "Do you have a known allergy?",
        "description": "patient has a known allergy",
        "keywords": [
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Allergic Reaction",
            "allergic reaction",
            "allergic reaction (diagnosis)",
            "allergic reaction (disorder)",
            "allergic reaction nos",
            "allergic reactions",
            "allergy",
            "allergy.",
            "reaction allergic (nos)",
            "reaction, allergic",
            "reactions, allergic",
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Allergic Reaction",
            "allergic reaction",
            "allergic reaction (diagnosis)",
            "allergic reaction (disorder)",
            "allergic reaction nos",
            "allergic reactions",
            "allergy",
            "allergy.",
            "reaction allergic (nos)",
            "reaction, allergic",
            "reactions, allergic"
        ]
    },
    {
        "code": "past experience",
        "display_name": "Past experience",
        "question": "patient has experienced similar symptoms in the past",
        "description": "patient has experienced similar symptoms in the past",
        "keywords": [
            "Symptoms",
            "general manifestation of disorders",
            "symptom",
            "symptom, nos",
            "symptoms",
            "symptoms (symptom)"
        ]
    },
    {
        "code": "allergy medication",
        "display_name": "Allergy to medication",
        "question": "Are you allergic to any medication?",
        "description": "patient is allergic to some medication",
        "keywords": [
            "Drug Allergy",
            "allergic reaction caused by drug",
            "allergic reaction to drug",
            "allergies drugs",
            "allergies medication",
            "allergies medications",
            "allergy drugs",
            "allergy medication",
            "allergy medications",
            "drug allergies",
            "drug allergy",
            "drug allergy (diagnosis)",
            "drug allergy nos",
            "drug hypersensitivities",
            "drug hypersensitivity",
            "drug hypersensitivity nos",
            "drugs hypersensitivity",
            "hypersensitivity, drug",
            "hypersensitivity; drug",
            "medication allergy",
            "medicine allergy",
            "Hypersensitivity",
            "allergic disorder",
            "allergic disorders",
            "allergic reaction",
            "allergic reaction (nos)",
            "allergic reaction caused by substance (disorder)",
            "allergic reaction to substance",
            "allergic reactions",
            "allergic state, nos",
            "allergy",
            "hypersensitivities",
            "hypersensitivity",
            "hypersensitivity reaction",
            "hypersensitivity reaction, nos",
            "hypersensitivity reactions",
            "hypersensitivity symptoms",
            "reaction hypersensitivity (nos)",
            "Allergic Reaction",
            "allergic reaction",
            "allergic reaction (diagnosis)",
            "allergic reaction (disorder)",
            "allergic reaction nos",
            "allergic reactions",
            "allergy",
            "allergy.",
            "reaction allergic (nos)",
            "reaction, allergic",
            "reactions, allergic"
        ]
    },
    {
        "code": "sexual activity",
        "display_name": "Sexual activity",
        "question": "patient is sexually active / patient was involved in sexual activity recently",
        "description": "patient is sexually active / patient was involved in sexual activity recently",
        "keywords": [
            "sexual activity", "physical intimacy"
        ]
    },
];

var disease_config = [
    {
        "name": "value",
        "type": "datalist",
        "values": all_diseases,
        "label": "Enter the disease(s)"
    },
    {
        "name": "status",
        "type": "select",
        "values": ["Yes", "No", "Maybe"],
        "label": "Does the patient have the disease(s)?"
    }
]

var tmp_list = all_antecendent_values.concat(all_symptom_values);
tmp_list = tmp_list.concat(all_diseases);
var medical_history_config = [
    {
        "name": "value",
        "type": "datalist",
        "values": tmp_list,
        "label": "Add symptom/disease/surgery/situation relevant to the patient's medical history."
    },
    {
        "name": "status",
        "type": "select",
        "values": [
            "Yes", "No",
            "The patient still suffers from the condition.",
            "The patient sufferred from the condition in the past.",
            "The patient did not suffer from the condition in the past.",
            "The patient is not sure about the status of the condition.",
        ],
        "label": "Status of the added condition(s)"
    },
    {
        "name": "when",
        "type": "text",
        "add_checkbox": ["inquire"],
        "label": "When did the patient start to experience the added condition?"
    },
    {
        "name": "frequency",
        "type": "text",
        "add_checkbox": ["inquire"],
        "label": "How frequently does the patient experience the added condition?"
    },
    {
        "name": "other",
        "type": "text",
        "add_checkbox": ["inquire"],
        "label": "Any additional information missing from the above fields"
    }
]
