var family_history_config = [
    {
        "name": "value",
        "type": "datalist",
        "values": [
            {
              "code": "allergies",
              "description": "",
              "display_name": "Allergies",
              "keywords": [
                "Hypersensitivity",
                "allergic disorder",
                "allergic disorders",
                "allergic reaction",
                "allergic reaction (nos)",
                "allergic reaction caused by substance (disorder)",
                "allergic reaction to substance",
                "allergic reactions",
                "allergic state, nos",
                "allergy",
                "hypersensitivities",
                "hypersensitivity",
                "hypersensitivity reaction",
                "hypersensitivity reaction, nos",
                "hypersensitivity reactions",
                "hypersensitivity symptoms",
                "reaction hypersensitivity (nos)",
                "Hypersensitivity",
                "allergic disorder",
                "allergic disorders",
                "allergic reaction",
                "allergic reaction (nos)",
                "allergic reaction caused by substance (disorder)",
                "allergic reaction to substance",
                "allergic reactions",
                "allergic state, nos",
                "allergy",
                "hypersensitivities",
                "hypersensitivity",
                "hypersensitivity reaction",
                "hypersensitivity reaction, nos",
                "hypersensitivity reactions",
                "hypersensitivity symptoms",
                "reaction hypersensitivity (nos)"
              ]
            },
            {
              "code": "pneumothorax",
              "description": "",
              "display_name": "Pneumothorax",
              "keywords": [
                "Pneumothorax",
                "collapsed lung",
                "pneumothorax",
                "pneumothorax (diagnosis)",
                "pneumothorax disorder",
                "pneumothorax nos",
                "pneumothorax, nos",
                "pneumothorax, unspecified",
                "Pneumothorax",
                "collapsed lung",
                "pneumothorax",
                "pneumothorax (diagnosis)",
                "pneumothorax disorder",
                "pneumothorax nos",
                "pneumothorax, nos",
                "pneumothorax, unspecified"
              ]
            },
            {
              "code": "asthma",
              "description": "",
              "display_name": "Asthma",
              "keywords": [
                "Asthma",
                "airway hyperreactivity",
                "asthma",
                "asthma (disorder)",
                "asthma disorders",
                "asthma, bronchial",
                "asthma, unspecified",
                "asthmas",
                "bronchial asthma",
                "Asthma",
                "airway hyperreactivity",
                "asthma",
                "asthma (disorder)",
                "asthma disorders",
                "asthma, bronchial",
                "asthma, unspecified",
                "asthmas",
                "bronchial asthma"
              ]
            },
            {
              "code": "cardiovascular disease",
              "description": "",
              "display_name": "Cardiovascular disease",
              "keywords": [
                "Cardiovascular Diseases",
                "cardiovascular disease",
                "cardiovascular disease, unspecified",
                "cardiovascular diseases",
                "cardiovascular disorder",
                "cardiovascular disorders",
                "cardiovascular disorders (diagnosis)",
                "cardiovascular system diseases",
                "cardiovascular system--diseases",
                "cv disorders",
                "cvd",
                "cvs disease",
                "disease (or disorder); cardiovascular",
                "disease or syndrome of cardiovascular system",
                "disease, cardiovascular",
                "disorder cardiovascular (nos)",
                "disorder of cardiovascular system (disorder)",
                "Cardiovascular Diseases",
                "cardiovascular disease",
                "cardiovascular disease, unspecified",
                "cardiovascular diseases",
                "cardiovascular disorder",
                "cardiovascular disorders",
                "cardiovascular disorders (diagnosis)",
                "cardiovascular system diseases",
                "cardiovascular system--diseases",
                "cv disorders",
                "cvd",
                "cvs disease",
                "disease (or disorder); cardiovascular",
                "disease or syndrome of cardiovascular system",
                "disease, cardiovascular",
                "disorder cardiovascular (nos)",
                "disorder of cardiovascular system (disorder)"
              ]
            },
            {
              "code": "pancreatic cancer",
              "description": "",
              "display_name": "Pancreatic cancer",
              "keywords": [
                "Pancreatic carcinoma",
                "carcinoma of pancreas",
                "carcinoma of the pancreas",
                "carcinoma pancreas",
                "carcinoma pancreatic",
                "carcinoma;pancreas",
                "exocrine pancreas carcinoma",
                "pancreas carcinoma",
                "pancreatic acinar carcinoma",
                "pancreatic cancer",
                "pancreatic carcinoma",
                "pancreatic carcinoma nos",
                "Malignant neoplasm of pancreas",
                "cancer of pancreas",
                "cancer of the pancreas",
                "cancer, pancreas",
                "malignant neoplasm of pancreas",
                "malignant neoplasm of pancreas, part unspecified",
                "malignant neoplasm of the pancreas",
                "malignant pancreatic neoplasm",
                "malignant tumor of pancreas (disorder)",
                "pancreas cancer",
                "pancreas cancer malignant",
                "pancreas cancers",
                "pancreatic cancer",
                "pancreatic cancers",
                "Pancreatic carcinoma",
                "carcinoma of pancreas",
                "carcinoma of the pancreas",
                "carcinoma pancreas",
                "carcinoma pancreatic",
                "carcinoma;pancreas",
                "exocrine pancreas carcinoma",
                "pancreas carcinoma",
                "pancreatic acinar carcinoma",
                "pancreatic cancer",
                "pancreatic carcinoma",
                "pancreatic carcinoma nos",
                "Malignant neoplasm of pancreas",
                "cancer of pancreas",
                "cancer of the pancreas",
                "cancer, pancreas",
                "malignant neoplasm of pancreas",
                "malignant neoplasm of pancreas, part unspecified",
                "malignant neoplasm of the pancreas",
                "malignant pancreatic neoplasm",
                "malignant tumor of pancreas (disorder)",
                "pancreas cancer",
                "pancreas cancer malignant",
                "pancreas cancers",
                "pancreatic cancer",
                "pancreatic cancers"
              ]
            },
            {
              "code": "croup",
              "description": "",
              "display_name": "Croup",
              "keywords": [
                "Subglottic laryngitis",
                "croup",
                "laryngitis",
                "pseudocroup",
                "spasmodic croup",
                "subglottic laryngitis",
                "viral croup",
                "Croup",
                "acute laryngotracheobronchitis",
                "acute obstructive laryngitis",
                "acute obstructive laryngitis [croup]",
                "croup",
                "croup (diagnosis)",
                "croup syndrome",
                "laryngotracheobronchitis, acute",
                "laryngotracheobronchitis; acute",
                "Subglottic laryngitis",
                "croup",
                "laryngitis",
                "pseudocroup",
                "spasmodic croup",
                "subglottic laryngitis",
                "viral croup",
                "Croup",
                "acute laryngotracheobronchitis",
                "acute obstructive laryngitis",
                "acute obstructive laryngitis [croup]",
                "croup",
                "croup (diagnosis)",
                "croup syndrome",
                "laryngotracheobronchitis, acute",
                "laryngotracheobronchitis; acute"
              ]
            },
            {
              "code": "psychiatric illness",
              "description": "",
              "display_name": "Psychiatric illness",
              "keywords": []
            },
            {
              "code": "myasthenia gravis",
              "description": "",
              "display_name": "Myasthenia gravis",
              "keywords": [
                "Myasthenias",
                "fatigable weakness",
                "fatigable weakness of limb muscles",
                "generalised muscle weakness due to defect at the neuromuscular junction",
                "generalized muscle weakness (due to defect at the neuromuscular junction)",
                "generalized muscle weakness due to defect at the neuromuscular junction",
                "myasthenia",
                "myasthenias",
                "myasthenic weakness",
                "proximal muscle weakness due to defect at the neuromuscular junction",
                "Myasthenias",
                "fatigable weakness",
                "fatigable weakness of limb muscles",
                "generalised muscle weakness due to defect at the neuromuscular junction",
                "generalized muscle weakness (due to defect at the neuromuscular junction)",
                "generalized muscle weakness due to defect at the neuromuscular junction",
                "myasthenia",
                "myasthenias",
                "myasthenic weakness",
                "proximal muscle weakness due to defect at the neuromuscular junction"
              ]
            },
            {
              "code": "anemia",
              "description": "",
              "display_name": "Anemia",
              "keywords": [
                "Anemia",
                "anaemia",
                "anaemia, nos",
                "anaemia, unspecified",
                "anemia",
                "anemia (diagnosis)",
                "anemia, nos",
                "anemias",
                "unspecified anaemia",
                "Anemia",
                "anaemia",
                "anaemia, nos",
                "anaemia, unspecified",
                "anemia",
                "anemia (diagnosis)",
                "anemia, nos",
                "anemias",
                "unspecified anaemia"
              ]
            },
            {
              "code": "cluster headaches",
              "description": "",
              "display_name": "Cluster headaches",
              "keywords": [
                "Cluster Headache",
                "cephalalgia, paroxysmal, nocturnal, orbital",
                "cluster headache",
                "cluster headaches",
                "headache histamine",
                "headache vasomotor",
                "headache, cluster",
                "headache;cluster",
                "histamine cephalgia",
                "histamine headache",
                "horton syndrome",
                "horton's neuralgia",
                "horton's syndrome",
                "hortons syndrome",
                "migrainous neuralgia",
                "neuralgia, ciliary",
                "neuralgias, ciliary",
                "syndrome, horton",
                "Cluster Headache",
                "cephalalgia, paroxysmal, nocturnal, orbital",
                "cluster headache",
                "cluster headaches",
                "headache histamine",
                "headache vasomotor",
                "headache, cluster",
                "headache;cluster",
                "histamine cephalgia",
                "histamine headache",
                "horton syndrome",
                "horton's neuralgia",
                "horton's syndrome",
                "hortons syndrome",
                "migrainous neuralgia",
                "neuralgia, ciliary",
                "neuralgias, ciliary",
                "syndrome, horton"
              ]
            },
            {
              "code": "lung cancer",
              "description": "",
              "display_name": "Lung cancer",
              "keywords": [
                "Carcinoma of lung",
                "cancer of lung",
                "cancer of the lung",
                "carcinoma lung",
                "carcinoma of lung",
                "carcinoma of lung (diagnosis)",
                "carcinoma of the lung",
                "carcinoma;respiratory",
                "carcinomas lung",
                "lung cancer",
                "lung carcinoma",
                "pulmonary carcinoma",
                "Malignant neoplasm of lung",
                "ca - lung cancer",
                "cancer of lung",
                "cancer pulmonary",
                "cancer, lung",
                "cancer, pulmonary",
                "cancers, lung",
                "lung cancer",
                "lung malignancies",
                "lung malignancy",
                "lung malignant tumors",
                "lung neoplasm malignant",
                "malignant lung neoplasm",
                "malignant neoplasm lung",
                "malignant neoplasm of lung",
                "malignant tumor of lung",
                "malignant tumor of lung (disorder)",
                "neoplasm malig;lung",
                "pulmonary cancer",
                "Carcinoma of lung",
                "cancer of lung",
                "cancer of the lung",
                "carcinoma lung",
                "carcinoma of lung",
                "carcinoma of lung (diagnosis)",
                "carcinoma of the lung",
                "carcinoma;respiratory",
                "carcinomas lung",
                "lung cancer",
                "lung carcinoma",
                "pulmonary carcinoma",
                "Malignant neoplasm of lung",
                "ca - lung cancer",
                "cancer of lung",
                "cancer pulmonary",
                "cancer, lung",
                "cancer, pulmonary",
                "cancers, lung",
                "lung cancer",
                "lung malignancies",
                "lung malignancy",
                "lung malignant tumors",
                "lung neoplasm malignant",
                "malignant lung neoplasm",
                "malignant neoplasm lung",
                "malignant neoplasm of lung",
                "malignant tumor of lung",
                "malignant tumor of lung (disorder)",
                "neoplasm malig;lung",
                "pulmonary cancer"
              ]
            },
            {
              "code": "mom asthma",
              "description": "",
              "display_name": "Mother has Asthma",
              "keywords": [
                "Asthma",
                "airway hyperreactivity",
                "asthma",
                "asthma (disorder)",
                "asthma disorders",
                "asthma, bronchial",
                "asthma, unspecified",
                "asthmas",
                "bronchial asthma",
                "Asthma",
                "airway hyperreactivity",
                "asthma",
                "asthma (disorder)",
                "asthma disorders",
                "asthma, bronchial",
                "asthma, unspecified",
                "asthmas",
                "bronchial asthma"
              ]
            },
            {
              "code": "lung disease",
              "description": "",
              "display_name": "Lung disease",
              "keywords": [
                "Lung diseases",
                "disease of lung, nos",
                "diseases of the lung",
                "diseases pulmonary",
                "diseases, pulmonary",
                "disorder lung",
                "lung disease",
                "lung disease nos",
                "lung diseases",
                "lung disorder",
                "lung disorders",
                "lungs--diseases",
                "pneumopathy",
                "pulmonary disease",
                "pulmonary disorder",
                "pulmonary disorders",
                "Chest>Lung",
                "chest>lung",
                "lung",
                "Lung",
                "lung",
                "lung structure",
                "lung structure (body structure)",
                "lung, nos",
                "lungs",
                "pulmo",
                "pulmonary",
                "pulmones",
                "respiratory system, lung",
                "set of lungs",
                "structure of lungs, unspecified",
                "Disease",
                "clinical disease and/or syndrome",
                "clinical disease or syndrome present",
                "clinical disease or syndrome, nos",
                "diagnoses, syndromes, and conditions (diagnosis)",
                "disease",
                "disease (disorder)",
                "disease (or disorder)",
                "disease or disorder",
                "disease or syndrome present",
                "disease or syndrome present, nos",
                "disease, nos",
                "disease/disorder",
                "diseases",
                "disorder",
                "disorders",
                "Lung diseases",
                "disease of lung, nos",
                "diseases of the lung",
                "diseases pulmonary",
                "diseases, pulmonary",
                "disorder lung",
                "lung disease",
                "lung disease nos",
                "lung diseases",
                "lung disorder",
                "lung disorders",
                "lungs--diseases",
                "pneumopathy",
                "pulmonary disease",
                "pulmonary disorder",
                "pulmonary disorders",
                "Chest>Lung",
                "chest>lung",
                "lung",
                "Lung",
                "lung",
                "lung structure",
                "lung structure (body structure)",
                "lung, nos",
                "lungs",
                "pulmo",
                "pulmonary",
                "pulmones",
                "respiratory system, lung",
                "set of lungs",
                "structure of lungs, unspecified",
                "Disease",
                "clinical disease and/or syndrome",
                "clinical disease or syndrome present",
                "clinical disease or syndrome, nos",
                "diagnoses, syndromes, and conditions (diagnosis)",
                "disease",
                "disease (disorder)",
                "disease (or disorder)",
                "disease or disorder",
                "disease or syndrome present",
                "disease or syndrome present, nos",
                "disease, nos",
                "disease/disorder",
                "diseases",
                "disorder",
                "disorders"
              ]
            },
            {
              "code": "heart disease",
              "description": "",
              "display_name": "Heart disease",
              "keywords": [
                "Heart Diseases",
                "cardiac disease",
                "cardiac diseases",
                "cardiac disorder",
                "cardiac disorders",
                "cardiopathy",
                "disease disorders heart",
                "disease hearts",
                "disorder cardiac (nos)",
                "heart disease",
                "heart disease (diagnosis)",
                "heart disease nos",
                "heart disease, unspecified",
                "heart diseases",
                "heart diseases: general terms",
                "heart disorders",
                "heart--diseases",
                "morbus; cordis",
                "rndx cardiac",
                "Heart Diseases",
                "cardiac disease",
                "cardiac diseases",
                "cardiac disorder",
                "cardiac disorders",
                "cardiopathy",
                "disease disorders heart",
                "disease hearts",
                "disorder cardiac (nos)",
                "heart disease",
                "heart disease (diagnosis)",
                "heart disease nos",
                "heart disease, unspecified",
                "heart diseases",
                "heart diseases: general terms",
                "heart disorders",
                "heart--diseases",
                "morbus; cordis",
                "rndx cardiac"
              ]
            },
            {
              "code": "cancer",
              "description": "",
              "display_name": "Cancer",
              "keywords": [
                "Malignant Neoplasms",
                "cancer",
                "cancers",
                "malignancy",
                "malignant neoplasm",
                "malignant neoplasm without specification of site",
                "malignant neoplasms",
                "malignant neoplastic disease",
                "malignant tumor",
                "neoplasm, malignant",
                "neoplasms, malignant",
                "Malignant Neoplasms",
                "cancer",
                "cancers",
                "malignancy",
                "malignant neoplasm",
                "malignant neoplasm without specification of site",
                "malignant neoplasms",
                "malignant neoplastic disease",
                "malignant tumor",
                "neoplasm, malignant",
                "neoplasms, malignant"
              ]
            },
            {
              "code": "similar symptoms",
              "description": "",
              "display_name": "a member of the patient's family has/had similar symptoms",
            }
        ],
        "label": "Select medical condition(s)"
    },
    {
        "name": "status",
        "type": "select",
        "values": ["Yes", "No", "Maybe"],
        "label": "Does anyone in the patient's family have the selected medical condition(s)?"
    },
    {
        "name": "relation",
        "type": "text",
        "label": "Relationship with the patient e.g. mother or a brother"
    },
    {
        "name": "other",
        "type": "text",
        "label": "Any additional information missing from the above fields"
    }
]
